### ISSUE TITLE
Need to index managed_purl_urls for use by audit tool

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/solrmarc-sw#139] opened 2016-09-20 22:52 UTC
change this in the schema.xml file:

from:
`<field name="managed_purl_urls" type="string" indexed="false" stored="true" multiValued="true"/>`

to:
`<field name="managed_purl_urls" type="string" indexed="true" stored="true" multiValued="true"/>`

**Comment by shelleydoljack** [comment] 2016-10-26 18:08
duplicate of #141

**Closed by shelleydoljack** 2016-10-26 18:08 UTC
